// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(PopulationDbContext))]
    partial class PopulationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Models.Actual", b =>
                {
                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Households")
                        .HasColumnType("Decimal(18,10)");

                    b.Property<decimal>("Population")
                        .HasColumnType("Decimal(18,10)");

                    b.HasKey("State");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("Models.Estimate", b =>
                {
                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("District")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Households")
                        .HasColumnType("Decimal(18,10)");

                    b.Property<decimal>("Population")
                        .HasColumnType("Decimal(18,10)");

                    b.HasKey("State", "District");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
